#!/usr/bin/env python3
"""Send today s pre-market scan results via Gmail.
Reads results/latest_scan_summary.txt and emails it.
Set these GitHub Secrets:
  GMAIL_USER         -> your Gmail address (e.g. you@gmail.com)
  GMAIL_APP_PASSWORD -> Gmail App Password (NOT your regular password)
  NOTIFY_EMAIL       -> where to send the alert (can be same as GMAIL_USER)
"""
import os
import smtplib
import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

gmail_user = os.environ.get("GMAIL_USER", "")
app_password = os.environ.get("GMAIL_APP_PASSWORD", "")
notify_email = os.environ.get("NOTIFY_EMAIL", gmail_user)

if not gmail_user or not app_password:
    print("[!] GMAIL_USER or GMAIL_APP_PASSWORD not set in GitHub Secrets. Skipping email.")
    exit(0)

summary_file = "results/latest_scan_summary.txt"
if not os.path.exists(summary_file):
    print("[!] No summary file found. Skipping email.")
    exit(0)

with open(summary_file, encoding="utf-8") as f:
    body_text = f.read()

today = datetime.datetime.utcnow().strftime("%d %b %Y")
subject = "NSE Pre-Market Picks - " + today + " (8:45 AM IST)"

msg = MIMEMultipart("alternative")
msg["Subject"] = subject
msg["From"] = gmail_user
msg["To"] = notify_email

# Plain text version
text_part = MIMEText(body_text, "plain", "utf-8")

# HTML version - styled
html_lines = body_text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
html_body = """
<html><body style="font-family:monospace; background:#f8fafc; padding:20px;">
<div style="max-width:600px; margin:auto; background:#fff; border:1px solid #e2e8f0; border-radius:8px; padding:24px;">
<h2 style="color:#0f172a; border-bottom:2px solid #059669; padding-bottom:8px;">
  NSE Pre-Market Scan &mdash; """ + today + """ (8:45 AM IST)
</h2>
<pre style="background:#f1f5f9; padding:16px; border-radius:6px; font-size:13px; line-height:1.6;">""" + html_lines + """</pre>
<p style="color:#64748b; font-size:12px; margin-top:16px;">
  Dalal Street Quantitative Trading Terminal &bull; Auto-generated by GitHub Actions
</p>
</div></body></html>
"""

html_part = MIMEText(html_body, "html", "utf-8")
msg.attach(text_part)
msg.attach(html_part)

try:
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(gmail_user, app_password)
        server.sendmail(gmail_user, notify_email, msg.as_string())
    print("Email sent to " + notify_email)
except Exception as e:
    print("Failed to send email: " + str(e))
    exit(1)
